repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
          - id: flake8
            additional_dependencies: [flake8-typing-imports==1.10.0]
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.5.4
      hooks:
          - id: autopep8
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.3.6
      hooks:
          - id: reorder-python-imports
            args: [--py3-plus]
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.0.1
      hooks:
          - id: add-trailing-comma
            args: [--py36-plus]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "" # Use the sha / tag you want to point at
      hooks:
          - id: prettier
    #should be checking js files?
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: "v7.14.0" # Use the sha / tag you want to point at
      hooks:
          - id: eslint
            additional_dependencies: ["eslint-plugin-compat", "babel-eslint"]
            args: ["--fix"]
